src/objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Building_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Building Interest</relationshipLabel>
        <relationshipName>Building_Interest</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Building Interest</relationshipLabel>
        <relationshipName>Building_Interest</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Building Interest</label>
    <nameField>
        <displayFormat>BI-{0000}</displayFormat>
        <label>BI #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Building Interest</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <formula>Location__r.Location_No_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Building</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Account.Primary_Member__r.Id =  Id , &quot;Yes&quot;,&quot;No&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>utm_campaign__c</fullName>
        <label>utm_campaign</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_campaign_id__c</fullName>
        <label>utm_campaign_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_content__c</fullName>
        <label>utm_content</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_medium__c</fullName>
        <label>utm_medium</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_source__c</fullName>
        <label>utm_source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_term__c</fullName>
        <label>utm_term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Start_Date__c</fullName>
        <label>Actual Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Email__c</fullName>
        <label>Contract Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Encoded_ID__c</fullName>
        <label>Encoded ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Reservable__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Reservable</label>
        <referenceTo>Opportunity_Reservable__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Member</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Referrer who referred to the current opportunity.</description>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Referred)</relationshipLabel>
        <relationshipName>ReferredOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tour_Outcome__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field will map the latest tour with the opportunity.</description>
        <label>Tour Outcome</label>
        <referenceTo>Tour_Outcome__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>utm_campaign__c</fullName>
        <label>utm_campaign</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_campaign_id__c</fullName>
        <label>utm_campaign_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_content__c</fullName>
        <label>utm_content</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_medium__c</fullName>
        <label>utm_medium</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_source__c</fullName>
        <label>utm_source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_term__c</fullName>
        <label>utm_term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_Reservable__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Opportunity_Offices</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reservable__c</fullName>
        <label>Reservable</label>
        <referenceTo>Reservable__c</referenceTo>
        <relationshipLabel>Opportunity Reservables</relationshipLabel>
        <relationshipName>Opportunity_Offices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Reservable</label>
    <nameField>
        <displayFormat>OO-{0000}</displayFormat>
        <label>Office ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Reservables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reservable__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Reservables</relationshipLabel>
        <relationshipName>Offices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unavailable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Reservable</label>
    <nameField>
        <label>Reservable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reservables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tour_Outcome__c.object
<CustomObject>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <formula>IF( ISBLANK( Lead__c ),  Opportunity__r.Lead_Source_Detail__c , Lead__r.Lead_Source_Detail__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Lead Source Detail</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Tour_Outcome</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tours</relationshipLabel>
        <relationshipName>Tours</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will be the contact who referred us the Tour. It can be a member, employee or a broker.</description>
        <inlineHelpText>Enter the contact who referred us the Tour. It can be a member, employee or a broker.</inlineHelpText>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tour Outcomes (Referrer)</relationshipLabel>
        <relationshipName>Tour_Outcomes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rescheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Rescheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>utm_campaign__c</fullName>
        <formula>Opportunity__r.utm_campaign__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>utm_campaign</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_campaign_id__c</fullName>
        <formula>Opportunity__r.utm_campaign_id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>utm_campaign_id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_content__c</fullName>
        <description>one of the utm_ parameters passed by websites and other external systems</description>
        <label>utm_content</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_medium__c</fullName>
        <formula>Opportunity__r.utm_medium__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>utm_medium</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_source__c</fullName>
        <formula>Opportunity__r.utm_source__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>utm_source</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_term__c</fullName>
        <description>one of the utm_ parameters passed by websites and other external systems</description>
        <label>utm_term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>uuid__c</fullName>
        <label>uuid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Tour Outcome</label>
    <nameField>
        <displayFormat>TRO-{0000}</displayFormat>
        <label>Tour Outcome ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Outcomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityTriggerHandlerTest.cls
/*
 * @ Created By : Anant Kumar
 * @ Created Date : 23 Feb 2016
 * @ Modified By : Amol Darekar
 * @ Modified Date : 13 June 2016
 */
@isTest
private class OpportunityTriggerHandlerTest {
    static testMethod void testOpportunityTriggerHandler(){
		
        Account accRec = TestingUtility.createAccount('strAccountName', true);
         Contact conRec = new Contact(
         		firstname	= 'John',
                lastname 	= 'Rambo',
                email 		= 'test@example.com',
                accountID	= accRec.Id,
                Status__c	= 'active'
            );
            insert conRec;
        Map<String, Id> oppRecordType = TestingUtility.getRecordTypeMapByName(Opportunity.sObjectType);
        
        Opportunity oppRec = TestingUtility.createOpportunity(accRec.Id, false);
        oppRec.Primary_Member__c = conRec.Id;
        oppRec.StageName = 'Tour Scheduled';
        oppRec.CloseDate = system.today().addDays(5);
        oppRec.RecordTypeId = oppRecordType.get('Office Space');
        TestingUtility.insertWithAssert(oppRec);
        
        Opportunity oppRec1 = TestingUtility.createOpportunity(accRec.Id, false);
        oppRec1.Primary_Member__c = conRec.Id;
        oppRec1.StageName = 'Tour Scheduled';
        oppRec1.CloseDate = system.today().addDays(5);
        oppRec1.RecordTypeId = oppRecordType.get('Enterprise Solutions');
        TestingUtility.insertWithAssert(oppRec1);
        
        Opportunity oppRec2 = TestingUtility.createOpportunity(accRec.Id, false);
        oppRec2.Primary_Member__c = conRec.Id;
        oppRec2.StageName = 'Tour Scheduled';
        oppRec2.CloseDate = system.today().addDays(5);
        oppRec2.RecordTypeId = oppRecordType.get('Enterprise Solutions');
        TestingUtility.insertWithAssert(oppRec2);
        
        Test.startTest();
        
        Building__c building1 = new Building__c(Name='building1',uuid__c = 'abc123');
		TestingUtility.insertWithAssert(building1);
		Reservable__c reservable = new Reservable__c(Name='reservable',Building__c=building1.Id);
		TestingUtility.insertWithAssert(reservable);
		Opportunity_Reservable__c oppReservable = new Opportunity_Reservable__c(Reservable__c=reservable.Id, Opportunity__c=oppRec1.Id);
		TestingUtility.insertWithAssert(oppReservable);
        
        Test.stopTest();
        
        oppRec1.Opportunity_Reservable__c = oppReservable.Id ;
        oppRec1.Building__c = building1.Id;
        oppRec1.Primary_Member__c = conRec.Id;
        oppRec1.Encoded_ID__c = '123';
        oppRec1.Actual_Start_Date__c = system.today().addDays(5);
        oppRec1.StageName = 'Closed Won';
        TestingUtility.updateWithAssert(oppRec1);
        
        Opportunity oppRec3 = TestingUtility.createOpportunity(accRec.Id, false);
        oppRec3.Primary_Member__c = conRec.Id;
        oppRec3.StageName = 'Tour Scheduled';
        oppRec3.LeadSource = 'WeLive.com';
        oppRec3.CloseDate = system.today().addDays(5);
        oppRec3.RecordTypeId = oppRecordType.get('Enterprise Solutions');
        TestingUtility.insertWithAssert(oppRec3);
    }
    
    static testMethod void testUpdateOppName(){
        Account accRec = TestingUtility.createAccount('strAccountName', true);
        //Contact conRec = TestingUtility.createContact(accRec.Id, 'strLastName', true);
         Contact conRec = new Contact(
         		firstname = 'John',
                lastname = 'Rambo',
                email = 'primarycontact@example.com',
                accountID = accRec.Id,
                Status__c = 'active'
            );
            insert conRec;
            
         Contact referrer1 = new Contact(
         		firstname = 'John',
                lastname = 'Rambo',
                email = 'referrer1@example.com',
                accountID = accRec.Id,
                Status__c = 'active'
            );
            insert referrer1;
        
        Reference__c reference1 = new Reference__c();
        reference1.Referenced_Email__c = 'primarycontact@example.com';
        reference1.IsActive__c = true;
        reference1.Referrer__c = referrer1.Id;
        reference1.Expires_On__c = Date.today().addDays(10);
        TestingUtility.insertWithAssert(reference1);
        
        Map<String, Id> oppRecordType = TestingUtility.getRecordTypeMapByName(Opportunity.sObjectType);
        
        Opportunity oppRec = TestingUtility.createOpportunity(accRec.Id, false);
        oppRec.Primary_Member__c = conRec.Id;
        oppRec.AccountId = accRec.Id;
        oppRec.StageName = 'Tour Scheduled';
        oppRec.CloseDate = system.today().addDays(5);
        oppRec.RecordTypeId = oppRecordType.get('Office Space');
        TestingUtility.insertWithAssert(oppRec);
        
        System.assertEquals(referrer1.Id, [SELECT Referrer__c FROM Opportunity WHERE Id=:oppRec.Id].Referrer__c);
        
        Opportunity oppRec1 = new Opportunity();
        oppRec1.StageName = 'Tour Scheduled';
        oppRec1.CloseDate = system.today().addDays(5);
        oppRec1.RecordTypeId = oppRecordType.get('Office Space');
        TestingUtility.insertWithAssert(oppRec1);
        
        Opportunity oppRec2 = TestingUtility.createOpportunity(accRec.Id, false);
        oppRec2.Primary_Member__c = conRec.Id;
        oppRec2.AccountId = accRec.Id;
        oppRec2.StageName = 'Tour Scheduled';
        oppRec2.CloseDate = system.today().addDays(5);
        oppRec2.RecordTypeId = oppRecordType.get('Enterprise Solutions');
        TestingUtility.insertWithAssert(oppRec2);
        
        List<Opportunity> oppList = new List<Opportunity>();
        Opportunity oppRec3 = TestingUtility.createOpportunity(accRec.Id, false);
        oppRec3.Primary_Member__c = conRec.Id;
        oppRec3.AccountId = accRec.Id;
        oppRec3.StageName = 'Tour Scheduled';
        oppRec3.CloseDate = system.today().addDays(5);
        oppRec3.RecordTypeId = oppRecordType.get('Enterprise Solutions');
        oppList.add(oppRec3);
        
        Opportunity oppRec4 = TestingUtility.createOpportunity(accRec.Id, false);
        oppRec4.Primary_Member__c = conRec.Id;
        oppRec4.AccountId = accRec.Id;
        oppRec4.StageName = 'Tour Scheduled';
        oppRec4.CloseDate = system.today().addDays(5);
        oppRec4.RecordTypeId = oppRecordType.get('Enterprise Solutions');
        oppList.add(oppRec4);
        
        TestingUtility.insertListWithAssert(oppList);
        
        Opportunity updatedOpp2 = [Select Id, Name From Opportunity Where Id=:oppRec2.Id];
        System.assertEquals('strAccountName - 1 - Enterprise', updatedOpp2.Name);
        System.assertEquals('strAccountName - 2 - Enterprise', [Select Id, Name From Opportunity Where Id=:oppList[0].Id].Name);
        
        Test.startTest();
        
        Building__c b = new Building__c(
				Name='b1',
				uuid__c = 'abc123'
		);
		insert b;
		
        Opportunity oppRec5 = TestingUtility.createOpportunity(accRec.Id, false);
        oppRec5.Primary_Member__c = conRec.Id;
        oppRec5.AccountId = accRec.Id;
        oppRec5.StageName = 'Tour Scheduled';
        oppRec5.CloseDate = system.today().addDays(5);
        oppRec5.Building__c	= b.Id;
        oppRec5.Actual_Start_Date__c = system.today();
        oppRec5.Encoded_ID__c = '10';
        TestingUtility.insertWithAssert(oppRec5);
        
	    Reservable__c r = new Reservable__c(Name='r1',Building__c=b.Id);
		insert r;
        Opportunity_Reservable__c opres = new Opportunity_Reservable__c(Reservable__c=r.Id, Opportunity__c=oppRec5.Id);
		insert opres;
        
        oppRec5.StageName = 'Contract Sent';
        TestingUtility.updateWithAssert(oppRec5);
        
        Test.stopTest();
    } 
    
    static testMethod void testcopyFieldFromLastOpportunity(){
     	Setting__c testSettings = new Setting__c();
       	testSettings.Name = 'OpportunityFromLatestOpportunity';
       	testSettings.Data__c = '{"LeadSource":{"name":"LeadSource","overwrite":false},"Lead_Source_Detail__c":{"name":"Lead_Source_Detail__c","overwrite":true},"utm_campaign__c":{"name":"utm_campaign__c","overwrite":true},"utm_campaign_id__c":{"name":"utm_campaign_id__c","overwrite":false},"utm_content__c":{"name":"utm_content__c","overwrite":false},"utm_medium__c":{"name":"utm_medium__c","overwrite":true},"utm_source__c":{"name":"utm_source__c","overwrite":false},"utm_term__c":{"name":"utm_term__c","overwrite":false}}';
       	TestingUtility.insertWithAssert(testSettings);
       	
     	Account accRec = TestingUtility.createAccount('strAccountName', true);
        Contact conRec = new Contact(
         		firstname = 'John',
                lastname = 'Rambo',
                email = 'test@example.com',
                accountID = accRec.Id,
                Status__c = 'active'
            );
            insert conRec;
        
        Map<String, Id> oppRecordType = TestingUtility.getRecordTypeMapByName(Opportunity.sObjectType);
    
     	Opportunity oppRec = new Opportunity();
     	oppRec.AccountId = accRec.Id;
     	oppRec.Primary_Member__c = conRec.Id;
     	oppRec.StageName = 'Inquirey';
     	oppRec.CloseDate = system.today();
     	oppRec.RecordTypeId = oppRecordType.get('Office Space');
        oppRec.Lead_Source_Detail__c = 'Test Lead Details'; 
     	oppRec.LeadSource = '44 Source';
     	oppRec.utm_campaign__c = 'Test Campaign';
     	oppRec.utm_campaign_id__c = '123';
     	oppRec.utm_content__c = 'Test Content';
     	oppRec.utm_medium__c = 'Test Medium';
     	oppRec.utm_source__c = 'Test Source';
     	oppRec.utm_term__c = 'Test Term';
     	insert oppRec;
     	
     	Opportunity oppnew = [select CreatedDate,LeadSource,Lead_Source_Detail__c,utm_campaign__c,utm_campaign_id__c,utm_content__c,utm_medium__c,utm_source__c,utm_term__c,Contract_Email__c from Opportunity where Id =: oppRec.Id];
     	Opportunity opportunity2 = new Opportunity();
     	opportunity2.AccountId = accRec.Id;
     	opportunity2.Primary_Member__c = conRec.Id;
     	opportunity2.StageName = 'Tour Scheduled';
     	opportunity2.CloseDate = system.today().addDays(5);
     	opportunity2.RecordTypeId = oppRecordType.get('Office Space');
     	oppRec.RecordTypeId = oppRecordType.get('Office Space');
        insert opportunity2;
     	
     	Opportunity newOpp = [select CreatedDate,LeadSource,Lead_Source_Detail__c,utm_campaign__c,utm_campaign_id__c,utm_content__c,utm_medium__c,utm_source__c,utm_term__c,Contract_Email__c from Opportunity where Id =: opportunity2.Id];
     	system.assertEquals('44 Source',newOpp.LeadSource);
     }
    
    static testMethod void testEncodedOpportunityID() {
		//pre-context
			Building__c b = new Building__c(
				Name='b1',
				uuid__c = 'abc123'
			);
			insert b;

			Opportunity o = new Opportunity(				
				CloseDate 	= system.today(),
				StageName 	= 'Inquire',
				Name 		= 'test Opoortunity',
				Building__c	= b.Id
			);
			insert o;		//test

		Test.startTest();
			o = [SELECT Encoded_Id__c FROM Opportunity WHERE id = :o.Id LIMIT 1];
			system.assertEquals(
				EncodingHandler.encode(o.Id),
				o.Encoded_Id__c,
				'The Opportunity was not correctly encoded.'
			);
			
		Test.stopTest();
	}
	
	static testMethod void testUpdatePrimaryMemberOnOpportunity(){
	       	
         	Account accRec     = TestingUtility.createAccount('strAccountName', true);
         		Contact conRec = new Contact(
              	firstname 	   = 'John',
               	lastname       = 'Rambo',
               	email          = 'test@example.com',
                accountID  	   = accRec.Id,
                Status__c      = 'active'
            );
            insert conRec;
            
       		Opportunity oppRec = new Opportunity();
       		//oppRec.Primary_Member__c = conRec.Id;
        	oppRec.AccountId = accRec.Id;
        	oppRec.StageName = 'Tour Scheduled';
        	oppRec.CloseDate = system.today().addDays(5);
        	//oppRec.RecordTypeId = oppRecordType.get('Office Space');
        	insert oppRec;
        	
        	//Test : ST-508 : Map opportunity with latest booked tour on its primary member with same location interested
        	
        	Account accountRec = TestingUtility.createAccount('strAccountName', true);
        	Contact primaryMember1 = TestingUtility.createContact(accountRec.Id, 'strLastName', false);
        	primaryMember1.Email = 'primarymember1@example.com';
        	TestingUtility.insertWithAssert(primaryMember1);
        
        	Building__c building1 = new Building__c(
                Name='NYC-Penn Station',
                uuid__c = 'abc123'
            );
            insert building1;
        
        	Building__c building2 = new Building__c(
                Name='building2',
                uuid__c = 'abc1232'
            );
            insert building2;
        
        	Tour_Outcome__c tour1 = new Tour_Outcome__c();
            tour1.Primary_Member__c = primaryMember1.Id;
            tour1.Status__c = 'Scheduled';
            tour1.Tour_Date__c = system.today().addDays(3);
        	tour1.Location__c = building1.Id;
            TestingUtility.insertWithAssert(tour1);
        	
        	Tour_Outcome__c tour2 = new Tour_Outcome__c();
            tour2.Primary_Member__c = primaryMember1.Id;
            tour2.Status__c = 'Scheduled';
            tour2.Tour_Date__c = system.today().addDays(3);
        	tour2.Location__c = building2.Id;
            TestingUtility.insertWithAssert(tour2);
        	
        	Tour_Outcome__c tour3 = new Tour_Outcome__c();
            tour3.Primary_Member__c = primaryMember1.Id;
            tour3.Status__c = 'Scheduled';
            tour3.Tour_Date__c = system.today().addDays(3);
        	tour3.Location__c = building1.Id;
            TestingUtility.insertWithAssert(tour3);
        
        	Opportunity opportunity1 = new Opportunity(
                AccountID                       = accountRec.Id,
                CloseDate                       = system.today(),
                Actual_Start_Date__c            = system.today(),
                StageName                       = 'Prospect',
                Name                            = 'test Opoortunity',
                Locations_Interested__c         = 'NYC-Penn Station',
                Primary_Member__c               = primaryMember1.Id
            );
            insert opportunity1;
        	System.assertEquals(tour3.Id, [SELECT Id, Name, Tour_Outcome__c FROM Opportunity WHERE Id=:opportunity1.Id].Tour_Outcome__c);
	}
	
	static testMethod void testDeleteBuildingInterests(){		
	       	Account accRec     = TestingUtility.createAccount('strAccountName', true);
         	Contact conRec = new Contact(
              	firstname 	   = 'John',
               	lastname       = 'Rambo',
               	email          = 'test@example.com',
                accountID  	   = accRec.Id,
                Status__c      = 'active'
            );
            insert conRec;
                      
       		Opportunity oppRec = new Opportunity();
       		//oppRec.Primary_Member__c = conRec.Id;
        	oppRec.AccountId = accRec.Id;
        	oppRec.StageName = 'Tour Scheduled';
        	oppRec.CloseDate = system.today().addDays(5);
        	//oppRec.RecordTypeId = oppRecordType.get('Office Space');
        	insert oppRec;
        	
			Building__c b = new Building__c(
				Name='b1',
				uuid__c = 'abc123'
			);
			insert b;
        	
        	Building_Interest__c b1 = new Building_Interest__c(
				Building__c = b.Id,
				//CurrencyIsoCode ='GBP-British Pound',
				Opportunity__c = oppRec.Id
			);
			
			insert b1;
        	delete oppRec;
        	
        	List<Building_Interest__c> bi = [SELECT Id FROM Building_Interest__c];
    		System.assertEquals(bi.size(),0);
    		Debug.log('Size of Building Interest ::'+bi);
	}

	static testMethod void testupdateContractEmail(){
		Debug.log(':: updateContractEmail ::');
	}


}