src/objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <label>Time Zone</label>
        <picklist>
            <picklistValues>
                <fullName>America/New_York</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>America/Chicago</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>America/Denver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>America/Los_Angeles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe/London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Jerusalem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe/Amsterdam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asia/Shanghai</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestListViewController.cls
/**
 * This class should contain all the test methods related ListViewController 
 * 
 * @author  Dipak Pawar
 * @date    25/06/2016
 */

@isTest
public class TestListViewController {
    
    /**
	 * ST-382 : Test method for get SObjectList.
	 * @author  Dipak Pawar
	 * @date    21/June/2016
	 */
	@isTest
    private static void testGetName() {
        List<SelectOption> options = new List<SelectOption>();
        options = ListViewController.getName();
        System.assert(options != null);
        System.assert(options.size() > 1);
    }
    
    /**
	 * ST-382 : Test method for get ListViews for particular SObject.
	 * @author  Dipak Pawar
	 * @date    21/June/2016
	 */
    @isTest
    private static void testGetViews() {
        Map<Id, string> views = new Map<Id, string>();
        views = ListViewController.getViews('Lead');
        System.assert(views != null);
        System.assert(views.size() > 1);
    }

    /**
	 * ST-382 : Test method for get ListView data.
	 * @author  Dipak Pawar
	 * @date    21/June/2016
	 */
    @isTest
    private static void testGetQuery() {
        sObject[] objectList;
        Building__c b = new Building__c(
            City__c = 'Test',
            Name = 'b1',
            uuid__c = 'bui001',
            time_zone__c = 'America/New_York'
        );
        insert b;
        objectList = ListViewController.Query('SELECT Id,Name From Building__c');
        System.assert(objectList != null);
        System.assert(objectList.size() > 0);
    }
}