src/objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maximum_Tour_Days__c</fullName>
        <defaultValue>21</defaultValue>
        <label>Maximum Tour Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Simultaneous_Tours__c</fullName>
        <label>Simultaneous Tours</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tour_Spacing__c</fullName>
        <label>Tour Spacing</label>
        <picklist>
            <picklistValues>
                <fullName>Half Hour</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hour</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Journey</fullName>
        <active>true</active>
        <businessProcess>Journey</businessProcess>
        <description>Let&apos;s provide beautiful journey to customers using this record type.</description>
        <label>Journey</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tour_Open_Hour__c.object
<CustomObject>
    <fields>
        <fullName>Building__c</fullName>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipName>Open_Hours</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <picklist>
            <picklistValues>
                <fullName>8:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:30PM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <picklist>
            <picklistValues>
                <fullName>8:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:30PM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Weekday__c</fullName>
        <label>Weekday</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Tour Open Hour</label>
    <nameField>
        <displayFormat>TOH-{0}</displayFormat>
        <label>Tour Open Hour Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tours Open Hours</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tour_Outcome__c.object
<CustomObject>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>WeWork</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WeLive</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <picklist>
            <picklistValues>
                <fullName>8:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:00PM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Tour Outcome</label>
    <nameField>
        <displayFormat>TRO-{0000}</displayFormat>
        <label>Tour Outcome ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Outcomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestScheduleTour.cls
@isTest
private class TestScheduleTour {
    @isTest
    private static void testSuccesfulSchedule() {
        Building__c b = new Building__c(
            City__c = 'Test',
            Name = 'Test',
            Simultaneous_Tours__c = '2',
            Tour_Spacing__c = 'Half Hour',
            Maximum_Tour_Days__c = 1
        );
        insert b;
		
		Tour_Schedule__c tour_Schedule = new Tour_Schedule__c(
            Building__c = b.Id,
            Simultaneous_Tours__c = '2',
            Tour_Spacing__c = 'Hour',
            Maximum_Tour_Days__c = 1,
            Product_Line__c = 'WeWork'
        );
        insert tour_Schedule;
		
        insert new Tour_Open_Hour__c[]{
            new Tour_Open_Hour__c(
                weekday__c = 'Monday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Tuesday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Wednesday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Thursday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Friday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Saturday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Sunday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            )
        };
        
        Lead l = new Lead(FirstName = 'Test', LastName = 'Test', Company = 'Test', Email = 'test@test.com');
        insert l;

        PageReference pr = new PageReference('/apex/ScheduleTour');
        pr.getParameters().put('leadId', l.Id);
        pr.getParameters().put('product_line', l.Product_Line__c);
        Test.setCurrentPageReference(pr);
        
        ScheduleTour sc = new ScheduleTour();
        
        SelectOption[] cities = sc.getCityList();
        System.assertEquals(1, cities.size());
        System.assertEquals('Test', cities[0].getValue());
        
        sc.selectedCity = 'Test';
        sc.citySelected();
        
        SelectOption[] buildings = sc.getBuildingListForSelectedLocation();
        System.assertEquals(1, buildings.size());
        System.assertEquals(b.Id, buildings[0].getValue());
        
        sc.selectedBuilding = b.Id;
        sc.buildingSelected();
        
        Date thisDate = Date.today().addDays(1);
        
        // Date out of range
        sc.newTour.Tour_Date__c = thisDate.addDays(2);
        sc.dateSelected();
        System.assertEquals(null, sc.newTour.Tour_Date__c);
        
        // Correct date
        sc.newTour.Tour_Date__c = thisDate;
        sc.dateSelected();
        
        // Time out of range
        sc.selectedTime = '4:00AM';
        sc.timeSelected();
        System.assertEquals(null, sc.selectedTime);
        
        // Correct time
        sc.selectedTime = '8:00AM';
        sc.timeSelected();
        
        // Incorrect time again
        sc.selectedTime = '4:00AM';
        sc.confirmTour();
        System.assertEquals(null, sc.selectedTime);

        // Correct time, schedule tour
        sc.selectedTime = '8:00AM';
        
        TriggersFlags.allowTourUpdates = false;
        sc.confirmTour();
        
        Tour_Outcome__c[] tours = [select Id, Status__c, Lead__c, Location__c, Tour_Date__c, Start_Time__c, End_Time__c from Tour_Outcome__c];
        system.assertNotEquals(
            0,
            tours.size(),
            'a tour record should be created'
        );

        Tour_Outcome__c tour = tours[0];

        System.assertEquals(l.Id, tour.Lead__c);
        System.assertEquals(b.Id, tour.Location__c);
        System.assertEquals(thisDate, tour.Tour_Date__c);
        System.assertEquals('8:00AM', tour.Start_Time__c);
        System.assertEquals('9:00AM', tour.End_Time__c);
        
    }
    
    @isTest
    private static void testScheduleTourFromOpportunity() {
        Building__c b = new Building__c(
            City__c = 'Test',
            Name = 'Test',
            Simultaneous_Tours__c = '2',
            Tour_Spacing__c = 'Half Hour',
            Maximum_Tour_Days__c = 1
        );
        insert b;
		
		Tour_Schedule__c tour_Schedule = new Tour_Schedule__c(
            Building__c = b.Id,
            Simultaneous_Tours__c = '2',
            Tour_Spacing__c = 'Hour',
            Maximum_Tour_Days__c = 1,
            Product_Line__c = 'WeWork'
        );
        insert tour_Schedule;
        
        insert new Tour_Open_Hour__c[]{
            new Tour_Open_Hour__c(
                weekday__c = 'Monday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Tuesday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Wednesday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Thursday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Friday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Saturday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Sunday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            )
        };
        Account accountRec = TestingUtility.createAccount('strAccountName', true);
        Opportunity opp = TestingUtility.createOpportunity(accountRec.Id, true);
        
        PageReference pr = new PageReference('/apex/ScheduleTour');
        pr.getParameters().put('oppId', opp.Id);
        Test.setCurrentPageReference(pr);
        
        ScheduleTour sc = new ScheduleTour();
        
        SelectOption[] cities = sc.getCityList();
        System.assertEquals(1, cities.size());
        System.assertEquals('Test', cities[0].getValue());
        
        sc.selectedCity = 'Test';
        sc.citySelected();
        
        SelectOption[] buildings = sc.getBuildingListForSelectedLocation();
        System.assertEquals(1, buildings.size());
        System.assertEquals(b.Id, buildings[0].getValue());
        
        sc.selectedBuilding = b.Id;
        sc.buildingSelected();
        
        Date thisDate = Date.today().addDays(1);
        
        // Date out of range
        sc.newTour.Tour_Date__c = thisDate.addDays(2);
        sc.dateSelected();
        System.assertEquals(null, sc.newTour.Tour_Date__c);
        
        // Correct date
        sc.newTour.Tour_Date__c = thisDate;
        sc.dateSelected();
        
        // Time out of range
        sc.selectedTime = '4:00AM';
        sc.timeSelected();
        System.assertEquals(null, sc.selectedTime);
        
        // Correct time
        sc.selectedTime = '8:00AM';
        sc.timeSelected();
        
        // Incorrect time again
        sc.selectedTime = '4:00AM';
        sc.confirmTour();
        System.assertEquals(null, sc.selectedTime);

        // Correct time, schedule tour
        sc.selectedTime = '8:00AM';
        
        TriggersFlags.allowTourUpdates = false;
        sc.confirmTour();
        
        Tour_Outcome__c[] tours = [select Id, Status__c, Opportunity__c, Lead__c, Journey__c, Location__c, Tour_Date__c, Start_Time__c, End_Time__c from Tour_Outcome__c];
        system.assertNotEquals(
            0,
            tours.size(),
            'a tour record should be created'
        );

        Tour_Outcome__c tour = tours[0];

        System.assertEquals(opp.Id, tour.Opportunity__c);
        System.assertEquals(b.Id, tour.Location__c);
        System.assertEquals(thisDate, tour.Tour_Date__c);
        System.assertEquals('8:00AM', tour.Start_Time__c);
        System.assertEquals('9:00AM', tour.End_Time__c);
        
    }
    /*
    @isTest
    private static void testScheduleTourFromJourney() {
        Building__c b = new Building__c(
            City__c = 'Test',
            Name = 'Test',
            Simultaneous_Tours__c = '2',
            Tour_Spacing__c = 'Half Hour',
            Maximum_Tour_Days__c = 1
        );
        insert b;
		
		Tour_Schedule__c tour_Schedule = new Tour_Schedule__c(
            Building__c = b.Id,
            Simultaneous_Tours__c = '2',
            Tour_Spacing__c = 'Hour',
            Maximum_Tour_Days__c = 1,
            Product_Line__c = 'WeWork'
        );
        insert tour_Schedule;
        
        insert new Tour_Open_Hour__c[]{
            new Tour_Open_Hour__c(
                weekday__c = 'Monday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Tuesday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Wednesday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Thursday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Friday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Saturday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            ),
            new Tour_Open_Hour__c(
                weekday__c = 'Sunday',
                start_time__c = '8:00AM',
                end_time__c = '8:00PM',
                Tour_Schedule__c = tour_Schedule.id,
                Building__c = b.id
            )
        };
        Journey__c journey = new Journey__c();
        journey.Name = 'Test Journey';
        journey.Stage__c = 'Started';
        journey.NMD_Next_Contact_Date__c= System.today();
        TestingUtility.insertWithAssert(journey);
        
        PageReference pr = new PageReference('/apex/ScheduleTour');
        pr.getParameters().put('journeyId', journey.Id);
        Test.setCurrentPageReference(pr);
        
        ScheduleTour sc = new ScheduleTour();
        
        SelectOption[] cities = sc.getCityList();
        System.assertEquals(1, cities.size());
        System.assertEquals('Test', cities[0].getValue());
        
        sc.selectedCity = 'Test';
        sc.citySelected();
        
        SelectOption[] buildings = sc.getBuildingListForSelectedLocation();
        System.assertEquals(1, buildings.size());
        System.assertEquals(b.Id, buildings[0].getValue());
        
        sc.selectedBuilding = b.Id;
        sc.buildingSelected();
        
        Date thisDate = Date.today().addDays(1);
        
        // Date out of range
        sc.newTour.Tour_Date__c = thisDate.addDays(2);
        sc.dateSelected();
        System.assertEquals(null, sc.newTour.Tour_Date__c);
        
        // Correct date
        sc.newTour.Tour_Date__c = thisDate;
        sc.dateSelected();
        
        // Time out of range
        sc.selectedTime = '4:00AM';
        sc.timeSelected();
        System.assertEquals(null, sc.selectedTime);
        
        // Correct time
        sc.selectedTime = '8:00AM';
        sc.timeSelected();
        
        // Incorrect time again
        sc.selectedTime = '4:00AM';
        sc.confirmTour();
        System.assertEquals(null, sc.selectedTime);

        // Correct time, schedule tour
        sc.selectedTime = '8:00AM';
        
        TriggersFlags.allowTourUpdates = false;
        sc.confirmTour();
        
        Tour_Outcome__c[] tours = [select Id, Status__c, Lead__c, Journey__c, Location__c, Tour_Date__c, Start_Time__c, End_Time__c from Tour_Outcome__c];
        system.assertNotEquals(
            0,
            tours.size(),
            'a tour record should be created'
        );

        Tour_Outcome__c tour = tours[0];

        System.assertEquals(journey.Id, tour.Journey__c);
        System.assertEquals(b.Id, tour.Location__c);
        System.assertEquals(thisDate, tour.Tour_Date__c);
        System.assertEquals('8:00AM', tour.Start_Time__c);
        System.assertEquals('8:30AM', tour.End_Time__c);
        
    }
    */
}