src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Company_Size__c</fullName>
        <label>Company Size</label>
        <picklist>
            <picklistValues>
                <fullName>1-5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6-20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21-50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51-100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>101-200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>201+</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <picklist>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ID_Kind__c</fullName>
        <formula>IF (
  OR(
     ISPICKVAL(Account.Type , &apos;Member&apos;),  
     ISPICKVAL(Account.Type , &apos;active&apos;),
     ISPICKVAL(Account.Type , &apos;Previous Member&apos;)
  ),
  &apos;member&apos;,
  &apos;potential&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ID Kind</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Primary_Member__c</fullName>
        <formula>IF( Account.Primary_Member__r.Id = Id, 
  true, 
  false
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Primary Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>af</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>af-ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sq</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sq-AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>gsw-FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>am-ET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-EG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-IQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-JO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-KW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-LB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-LY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-OM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-SY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-TN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-YE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hy-AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>as-IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>az</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>az-Cyrl-AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>az-Latn-AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ba-RU</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Account.Primary_Member__r.Id =  Id , &quot;Yes&quot;,&quot;No&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Interests__c</fullName>
        <label>Product Interests</label>
        <picklist>
            <picklistValues>
                <fullName>Wework.com Membership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residential Space</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>WeWork</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WeLive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountServices.cls
public class AccountServices {

    public Account a    {get; set;}
    public Contact c    {get; set;}

	public class AccountServicesException extends Exception {}
    
	// Load init from Web Handler
	public AccountServices(WWTypes.InboundLead pInboundLead) {

        // Load Account
		this.a = this.get_account_by_uuid(pInboundLead.account_uuid);

		// Load Contact
		this.c = this.get_contact_by_uuid(pInboundLead.contact_uuid);

        // Account exists
        if (this.a != null) {
            
            // Contact not exists
            if (this.c == null) {
                insert_contact_by_web(pInboundLead);
            }
            // Contact exists
            else if (this.c != null) {
                 Debug.log('In Account Service contact != null');
                // Do nothing if belongs to Account
                if (this.c.AccountId != this.a.Id) {
                    
                    // If Contact is Primary Member on another Account
                    if (this.c.Is_Primary_Member__c) {
                        throw new AccountServicesException('Contact is Primary Member on different Account');
                    }
                    // Contact is a regular member on another Account, move to this Account
                    else {
                    	Debug.log('In Account Service contact else');
                    	 // ST-164 :-Endpoint Tour: Should not update existing Contact's Account
                        //update_contact_account();
                    }
                }
            }
        }
        // Account not exists
        else {
            // Contact Exists
            if (this.c != null) {
                // If Contact is Primary Member on another Account
                if (this.c.Is_Primary_Member__c) {
                    throw new AccountServicesException('Contact is Primary Member on different Account');
                }
                // Contact is a regular member on another Account, create Account and transfer Contact
                else {
                    insert_account_by_web(pInboundLead);
                    update_contact_account();
                }
            }
            // Contact does not exist
            else {
                //System.debug(LoggingLevel.ERROR,'/*/*/*/*/ Cont Doest Exits'+pInboundLead);
                Debug.log('In Account Service Insert account and contact');
                insert_account_by_web(pInboundLead);
                insert_contact_by_web(pInboundLead);
            }
        }
    }
    
    private void insert_account_by_web(WWTypes.InboundLead pInboundLead) {
        
        this.a = new Account(
            Name = pInboundLead.company_name,
            UUID__c = pInboundLead.account_uuid,
            Company_Size__c = pInboundLead.company_size,
            Lead_Source__c = 'Id'
        );
        
        insert this.a;
    }

    private void insert_contact_by_web(WWTypes.InboundLead pInboundLead) {
        
        this.c = new Contact(
            FirstName = pInboundLead.first_name,
            LastName = pInboundLead.last_name,
            Phone = pInboundLead.phone,
            Email = pInboundLead.email,
            Locale__c = pInboundLead.locale,
            Product_Interests__c = LeadServices.getProduct_Interests(pInboundLead.product_interests),
            Country_Code__c = pInboundLead.country_code,
            Product_Line__c = pInboundLead.product_line,
            UUID__c = pInboundLead.contact_uuid,
            AccountId = this.a.Id,
            LeadSource = 'Id'
        );
        
        insert this.c;
        
        //reload
        this.c = get_contact_by_id(this.c.Id);        

        // Reload records as Contact might have been set as Primary Member for Account
        if (this.a.Primary_Member__c == null) {

            this.a = get_account_by_id(this.a.Id);
		}

        //explicit set of contact_uuid to the new one
        pInboundLead.contact_uuid = this.c.uuid__c;
        
	}

    private void update_contact_account() {
        
        this.c.AccountId = this.a.Id;
        update this.c;

        // Reload records as Contact might have been set as Primary Member for Account
        if (this.a.Primary_Member__c == null) {
            this.c = get_contact_by_id(this.c.Id);
            this.a = get_account_by_id(this.a.Id);
		}
    }
    
	private Contact get_contact_by_uuid(String uuid) {		
        //dramatic exit
        if (uuid == null || uuid == '') return null;

		Contact[] Cs = [SELECT Id,
                               AccountId,
                               OwnerId,
                               Is_Primary_Member__c,
                               FirstName,
                               LastName,
                               Phone,
                               Email,
                               Product_Interests__c,
                               Product_Line__c,	
                               UUID__c,
                               Id_Kind__c
						FROM Contact 
						WHERE UUID__c = :uuid 
						ORDER BY CreatedDate DESC
						LIMIT 1];

		return Cs.size() > 0 ? Cs[0] : null;
	}

	private Contact get_contact_by_id(Id contactId) {
        
		Contact[] Cs = [SELECT Id,
                               AccountId,
                               OwnerId,
                               Is_Primary_Member__c,
                               FirstName,
                               LastName,
                               Phone,
                               Email,
                               Product_Interests__c,
                               Product_Line__c,
                               UUID__c,
                               Id_Kind__c
						FROM Contact 
						WHERE Id = :contactId];

		return Cs.size() > 0 ? Cs[0] : null;
	}
    
	private Account get_account_by_uuid(String uuid) {
        //dramatic exit
        if (uuid == null || uuid == '') return null;
        
		Account[] Accs = [SELECT Id, OwnerId, Primary_Member__c
						  FROM Account
						  WHERE UUID__c = :uuid 
						  ORDER BY CreatedDate DESC
						  LIMIT 1];

		return Accs.size() > 0 ? Accs[0] : null;
	}
    
	private Account get_account_by_id(Id accountId) {
        
		Account[] Accs = [SELECT Id, OwnerId, Primary_Member__c
						  FROM Account
						  WHERE Id = :accountId];

		return Accs.size() > 0 ? Accs[0] : null;
	}
}