src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Journey__c.object
<CustomObject>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <fields>
        <fullName>Lost_Reason__c</fullName>
        <description>Reason why we lost the journey</description>
        <label>Lost Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fake Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unrelated to Sales Inquiries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary Contact of the Journey</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If journey is for a Lead this will be the Primary Lead. Only Primary Contact or Primary Lead can be specified not both.</description>
        <label>Primary Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Journeys (Referrer)</relationshipLabel>
        <relationshipName>Journeys1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage of the Journey, which will tell us the maximum progress the customer has made.

It will not give us latest Stage but will give maximum stage that is if the journey is completed or lost, or if it is stuck in waitlist.</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Tour Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tour Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed-Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed-Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <description>Globally Unique Identifier of the record used by all systems at WeWork</description>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/JourneyTriggerHandler.cls
/*
*	Created By   	: Dipak Pawar
*	Created Date 	: 06-07-2016
*	Summary       	: This class will contain the business logic of JourneyTriggers.
* 	Issue No.		: 
*/
public class JourneyTriggerHandler {
    public static void setPrimaryLeadToUnqualified() {
    	map<String,String> mapJourenyStatus = new map<String,String>();
        list<LeadJourneyStatusController> lstLeadJourneyStatus = new list<LeadJourneyStatusController>();
        Setting__c JSONLeadJourneyStatus = Settings.get('LeadJourneyTrigger');
    	if(JSONLeadJourneyStatus != null){
	    	lstLeadJourneyStatus = (List<LeadJourneyStatusController>)JSON.deserialize(JSONLeadJourneyStatus.Data__c, List<LeadJourneyStatusController>.class);
	       	if(lstLeadJourneyStatus != null && lstLeadJourneyStatus.size() > 0)
	    	{
	    		for(LeadJourneyStatusController currentStatus : lstLeadJourneyStatus)
	    		{
	    			mapJourenyStatus.put(currentStatus.JourneyStage,currentStatus.LeadStatus);
	    		}	    		
	    	}
	    	String leadStatus = mapJourenyStatus.values()[0];
	    	set<string> journeyStage = mapJourenyStatus.keySet();
	        List<Journey__c> lstJourneys = new List<Journey__c>();
	    	Map<Id, String> mapLeadIds = new Map<Id, String>();
	    	
	        for(Journey__c currentJourney : (List<Journey__c>)Trigger.New){
	            Journey__c oldJourney = (Journey__c)Trigger.oldMap.get(currentJourney.Id);
	            if(oldJourney.Stage__c != currentJourney.Stage__c && oldJourney.Stage__c == 'Started' && journeyStage.contains(currentJourney.Stage__c)){
	                         mapLeadIds.put(currentJourney.Primary_Lead__c, currentJourney.Lost_Reason__c);
	            }	            
	        }
	        set<Id> setLeadIds = new set<Id>(mapLeadIds.keySet());
	        if(setLeadIds.size() > 0) {
	         	List<Lead> lstLeads = [select Id, Email, Status, Unqualified_Reason__c from Lead where Id in :setLeadIds and Status !=: leadStatus];
	         	if(lstLeads!= null && lstLeads.size() > 0)
	         	{
		         	for(Lead currentLead : lstLeads){
		                currentLead.Status = leadStatus;
		                currentLead.Unqualified_Reason__c = mapLeadIds.get(currentLead.Id);
		            }
		            update lstLeads;
	         	}
         	}
    	}
	}
	
	public class LeadJourneyStatusController 
    {
    	public string LeadStatus{get;set;}
    	public string JourneyStage{get;set;}
    }
    
    /*
*	Created By   	: Samadhan Kadam
*	Created Date 	: 19-07-2016
*	Summary       	: This method get active Referrence record and set Referrer__c field value of lead or contact based on email Id.
* 	Issue No.		: 533
*/
    public static void updateActiveReferrerOnJourney(){
    	Set<String> setLeadEmails = new Set<String>();
    	Set<String> setContactEmails = new Set<String>();
    	Set<Id> setContact = new Set<Id>();
    	Set<Id> setLead = new Set<Id>();
    	Map<Id,String> mapOfLead = new Map<Id,String>();
    	Map<Id,String> mapOfContact = new Map<Id,String>();
    	
    	for(Journey__c journey :  (List<Journey__c>)Trigger.New){
    		if(journey.Primary_Contact__c != null){
 				setContact.add(journey.Primary_Contact__c);
			}  			
    		if(journey.Primary_Lead__c != null){
				setLead.add(journey.Primary_Lead__c);
    		}
    	}		  	
    	for(Contact contact :  [select Id,Email,Referrer__c from Contact WHERE Id IN:setContact]){
  				setContactEmails.add(contact.Email.toLowerCase());
  				mapOfContact.put(contact.Id,contact.Email.toLowerCase());
    	}
		if(setContactEmails.size() > 0){
    		Map<String,Id> mapOfContactActiveReference = ReferenceHandler.getActiveReference(setContactEmails);
    		if(mapOfContactActiveReference != null && mapOfContactActiveReference.size() > 0){
    			for(Journey__c journey : (List<Journey__c>)Trigger.New){
            		journey.Referrer__c = mapOfContactActiveReference.get(mapOfContact.get(journey.Primary_Contact__c));
    			 }
    		}
    	}
    	for(Lead lead :  [select Id,Email,Referrer__c from Lead WHERE Id IN:setLead]){
  				setLeadEmails.add(lead.Email.toLowerCase());
  				mapOfLead.put(lead.Id,lead.Email.toLowerCase());		
    	}
    	if(setLeadEmails.size() > 0){
    	  Map<String,Id> mapOfLeadActiveReference = ReferenceHandler.getActiveReference(setLeadEmails);
    		if(mapOfLeadActiveReference != null && mapOfLeadActiveReference.size() > 0){
  				for(Journey__c journey : (List<Journey__c>)Trigger.New){
            		journey.Referrer__c = mapOfLeadActiveReference.get(mapOfLead.get(journey.Primary_Lead__c));
    			 }
    		}
    	}
   	} 
   	
   	/*
	* Created By   	: Mayuresh Ghodke
	* Created Date 	: 29-07-2016
	* Comment		: Generate UUID for new Journey.
	*/
   	public static void generateUUID() {
		for (Journey__c journeyRec : (List<Journey__c>)Trigger.new) {
				journeyRec.UUID__c = UUIDHandler.generateVersion4();
		}
    }
}