src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <picklist>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ID_Kind__c</fullName>
        <formula>IF (
  OR(
     ISPICKVAL(Account.Type , &apos;Member&apos;),  
     ISPICKVAL(Account.Type , &apos;active&apos;),
     ISPICKVAL(Account.Type , &apos;Previous Member&apos;)
  ),
  &apos;member&apos;,
  &apos;potential&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ID Kind</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <label>Lead Source Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>af</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>af-ZA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sq</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>sq-AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>gsw-FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>am-ET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-DZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-EG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-IQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-JO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-KW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-LB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-LY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-OM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-SY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-TN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ar-YE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>hy-AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>as-IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>az</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>az-Cyrl-AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>az-Latn-AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ba-RU</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>I don&apos;t know</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple cities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amsterdam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlanta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Be&apos;er Sheva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Berkeley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Berlin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boston</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chicago</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Herzliya</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hing Kong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>London</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los Angeles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mexico City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miami</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montreal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New York City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Philadelphia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Francisco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Jose</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seattle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seoul</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shanghai</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tel Aviv</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wahington, D.C.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Interests__c</fullName>
        <label>Product Interests</label>
        <picklist>
            <picklistValues>
                <fullName>Wework.com Membership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residential Space</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>WeWork</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WeLive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>utm_campaign__c</fullName>
        <label>utm_campaign</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_campaign_id__c</fullName>
        <label>utm_campaign_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_content__c</fullName>
        <label>utm_content</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_medium__c</fullName>
        <label>utm_medium</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_source__c</fullName>
        <label>utm_source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_term__c</fullName>
        <label>utm_term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Default</fullName>
        <active>true</active>
        <label>Default</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TaskServices.cls
public with sharing class TaskServices {
	public Lead k {get;set;}
	public Contact c {get;set;}
	public Boolean is_first_touch {get; set;}

	public TaskServices() {		
	}

	public TaskServices(LeadServices ls) {
		this.k = ls.k;
		this.c = ls.c;
		this.is_first_touch = ls.is_first_touch;
	}
    
    public TaskServices(Lead k, Contact c, Boolean is_first_touch) {
        this.k = k;
        this.c = c;
        this.is_first_touch = is_first_touch;
    }

	public Task create_task_from_email(Messaging.inboundEmail email,
																Messaging.InboundEnvelope env) {
		//create a new task
		Task t = new Task(
			type 			= 'Email',
			subject 		= email.subject,
			WhoId 			= this.getWhoId(),
			ownerId 		= this.getOwnerId(),
			description 	= this.getContentBody(email.subject, email.plainTextBody),
			WhatId 			= this.getWhatId(),
			interaction__c 	= 'Inbound',
			first_touch__c  = this.is_first_touch
		);

		return t;
	}

	public Task create_task_from_web(WWTypes.InboundLead pInboundLead) {
		//create a new task
		Task t = new Task(
			type 						= 'Website', //review this
			subject 				= 'Inbound Lead submission', //default we will update it later
			WhoId 					= this.getWhoId(),
			ownerId 				= this.getOwnerId(),
			description 		= 'Inbound Lead', //review this
			WhatId 					= null, //review this
            Locale__c 		= pInboundLead.locale,
            Product_Interests__c = LeadServices.getProduct_Interests(pInboundLead.product_interests),
            Country_Code__c = pInboundLead.country_code,
			interaction__c 	= 'Inbound',
			Product_Line__c = pInboundLead.product_line,
			first_touch__c  = this.is_first_touch
           // Market__c		= pInboundLead.market
		);

		String id_kind = this.getContactIDKind();

		//check if member
		if (id_kind != null && id_kind.equalsIgnoreCase('Member'))	{
			t.subject = 'Current Member followup';
		}

		//check if it's a tour
		if (pInboundLead.tour_date != null && pInboundLead.tour_building_uuid != null) {
			t.subject = 'Tour Scheduled';
		}

		//custom bindings

		//utms
		t.utm_campaign__c 		= pInboundLead.utm_campaign;
		t.utm_campaign_id__c	= pInboundLead.utm_campaign_id;
		t.utm_content__c			= pInboundLead.utm_content;
		t.utm_medium__c				= pInboundLead.utm_medium;
		t.utm_source__c				= pInboundLead.utm_source;
		t.utm_term__c					= pInboundLead.utm_term;

		//lead source
		t.lead_source__c 				= pInboundLead.lead_source;
		t.lead_source_detail__c = pInboundLead.lead_source_detail;

    // review this
    if (pInboundLead.tour_date != null) {
        t.activityDate = pInboundLead.tour_date;
    }

		return t;	
	}

	private String getContentBody(String pSubject, String pPlainTextBody) {
		String result;
		try {
			result = String.format(
								'Subject: {0} \nBody: \n\n{1}', 
								new String[]{
									pSubject != null ? pSubject : 'n/a',
									pPlainTextBody != null ? pPlainTextBody : 'n/a'
								}
			);
		}
		catch(Exception pEx) {
			result = ''; //default value
		}
	
		return result;
	}

	private String getContactIDKind() {
		String result = null;
		try {
			result = this.c.id_kind__c;
		}
		catch(Exception pEx) {
			result = null; //default value
		}
		
		return result;
	}

	private Id getWhoId() {
		Id result;
	
		//get lead id or converted contact id
		if (this.k != null) {
			result = this.k.isConverted ? this.k.convertedContactId : this.k.id;	
		}
		
		//get contact id or accept previous lead/contact id value
		result = this.c != null ? this.c.id : result;

		return result;
	}

	private Id getOwnerId () {
		Id result;
		try {

			//get owner from lead
			if (this.k != null) {
				result = this.k.isConverted ? 
								this.k.convertedContact.ownerId :
								this.k.ownerId;	
			}

			//get owner from contact
			if (this.c != null) {
				result = this.c.ownerId;	
			}			

			result = [	SELECT isActive 
									FROM User 
									WHERE id = :result 
									LIMIT 1
								].isActive ?
								result :
								UserInfo.getUserId();		
		}
		catch(Exception pEx) {
			result = UserInfo.getUserId(); //default value aka fallback user
		}
		
		return result;
	}

	private Id getWhatId() {
		Id result = null;

		if (this.k != null) {
			result = this.k.isConverted ? 
								OpportunityServices.getMostRecentOpportunityId(this.k.convertedAccountId) : 
								null;
		}

		if (this.c != null) {
			result = OpportunityServices.getMostRecentOpportunityId(this.c.AccountId);
		}

		return result;
	}
}