src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <formula>if( Account.Primary_Member__r.Id =  Id , &quot;Yes&quot;,&quot;No&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Primary Member</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Member</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Referrer who referred to the current opportunity.</description>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Referred)</relationshipLabel>
        <relationshipName>ReferredOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tour_Date__c</fullName>
        <label>Tour Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tour_Outcome__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field will map the latest tour with the opportunity.</description>
        <label>Tour Outcome</label>
        <referenceTo>Tour_Outcome__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Journey</fullName>
        <active>true</active>
        <businessProcess>Journey</businessProcess>
        <description>Let&apos;s provide beautiful journey to customers using this record type.</description>
        <label>Journey</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tour_Outcome__c.object
<CustomObject>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <picklist>
            <picklistValues>
                <fullName>42 Floors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ads-twitter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adwords</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Broker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craigslist Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Id</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbound Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facebook</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LinkedIn Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Olark Chat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Email/Cold Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Twitter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WeWork.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WeWork.com Health Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WeWorkLabs.com Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WeWork Magazine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yelp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>servicefriendz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tours</relationshipLabel>
        <relationshipName>Tours</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This will be the contact who referred us the Tour. It can be a member, employee or a broker.</description>
        <inlineHelpText>Enter the contact who referred us the Tour. It can be a member, employee or a broker.</inlineHelpText>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tour Outcomes (Referrer)</relationshipLabel>
        <relationshipName>Tour_Outcomes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheduled_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scheduled With</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Tours (Scheduled With)</relationshipLabel>
        <relationshipName>Tours_Scheduled_With</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <picklist>
            <picklistValues>
                <fullName>8:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:00AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:30AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:00PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7:30PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:00PM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rescheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Rescheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tour_Date__c</fullName>
        <label>Tour Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tour_Outcome__c</fullName>
        <label>Tour Outcome</label>
        <picklist>
            <picklistValues>
                <fullName>Very Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undecided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Tour Outcome</label>
    <nameField>
        <displayFormat>TRO-{0000}</displayFormat>
        <label>Tour Outcome ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Outcomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Triggers__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>We are going to use this object to activate or deactivate various triggers we will be writing so we can easily deactivate triggers in case of errors or mass upload if required.</description>
    <fields>
        <fullName>Lead_ConvertLeadsToJourneys__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This trigger is use to call method &apos;ConvertLeadsToJourneys&apos; from lead converter class which conver lead into contact and opprtunity</description>
        <label>Lead ConvertLeadsToJourneys</label>
        <type>Checkbox</type>
    </fields>
    <label>Triggers</label>
</CustomObject>

src/classes/RESTInboundLeadTest.cls
@isTest
private class RESTInboundLeadTest {
    static Boolean settingsInitialized = false;
    static LeadConvertor.JourneySettings settingJourney;
    
    static void initFieldMappings() {
        Debug.turnDebugOn();

        if( settingsInitialized )
            return;
        
        /*
        Settings.FieldMappings leadToContactMappings = new Settings.FieldMappings();
        leadToContactMappings.version = 1;
        leadToContactMappings.mappings = new Map<String, Settings.MappedField>();
        leadToContactMappings.mappings.put('Name', new Settings.MappedField('Name'));
        leadToContactMappings.mappings.put('Email', new Settings.MappedField('Email'));
        Settings.saveFieldMappings( 'LeadToContact', leadToContactMappings);
        
        Settings.FieldMappings leadToJourneyMappings = new Settings.FieldMappings();
        leadToJourneyMappings.version = 1;
        leadToJourneyMappings.mappings = new Map<String, Settings.MappedField>();
        leadToJourneyMappings.mappings.put('Name', new Settings.MappedField('Name'));
        leadToJourneyMappings.mappings.put('Lead_Source__c', new Settings.MappedField('LeadSource'));
        Settings.saveFieldMappings( 'LeadToJourney', leadToJourneyMappings);

        Settings.FieldMappings leadToActivityMappings = new Settings.FieldMappings();
        leadToActivityMappings.version = 1;
        leadToActivityMappings.mappings = new Map<String, Settings.MappedField>();
        leadToJourneyMappings.mappings.put('Lead_Source__c', new Settings.MappedField('LeadSource'));
        Settings.saveFieldMappings( 'LeadToActivity', leadToActivityMappings);
		*/
        
        Account account = new Account(Name = 'Dummy Lead Conversion Account');
        insert account;

        //Initiralize Trigger settings
        /*Triggers__c triggers = Triggers__c.getOrgDefaults();
        Debug.Log('Triggers Existing : ' + triggers);
        triggers.Lead_ConvertLeadsToJourneys__c = true;
        upsert triggers;
        Debug.Log('Triggers Saved : ' + triggers);*/

        Setting__c[] settingsToInsert = new List<Setting__c>();
        settingJourney = new LeadConvertor.JourneySettings();
        settingJourney.NextCallInDaysFromLeadCreation = 2;
        settingJourney.NewLeadActivityFields = null;
        settingJourney.NewJourneyFields = null;
        settingJourney.NoCompanyAccountId = account.Id;
        settingsToInsert.add(new Setting__c(Name = 'Journey', Data__c = JSON.serialize(settingJourney)));
        insert settingsToInsert;
        
        /*Setting__c testSettings = new Setting__c();
        testSettings.Name = 'LeadJourneyTrigger';
        testSettings.Data__c = '[{"LeadStatus":"Unqualified","JourneyStage":"Completed-Lost"}]';
        TestingUtility.insertWithAssert(testSettings);*/
        
        Profile weworkSystemAdmin = [SELECT Id FROM Profile WHERE Name='WeWork Standard User'];
        Map<String,Object> userRecordMap = new Map<String,Object>();
        userRecordMap.put('LastName','Last Name 1');
        userRecordMap.put('Username','testweworkuser1@example.com');
        userRecordMap.put('Email','testweworkuser1@example.com');
        User testUser = TestingUtility.insertUserWithAssert(weworkSystemAdmin.Id, userRecordMap, true); 
        
        Setting__c testSettings = new Setting__c();
        testSettings.Name = 'Lead:Lead and Lead Source Details';
        testSettings.Data__c = '{"LeadSource":["Broker"], "LeadSourceDetails":["Broker1","Broker2" ]}]';
        TestingUtility.insertWithAssert(testSettings);
        
        testSettings = new Setting__c();
        testSettings.Name = 'User/Queue Journey Creation';
        testSettings.Data__c = '{"allowedUsers":[{"userName":"'+ testUser.Username +'","Id":"'+testUser.Id +'"}],"allowedQueues":[]}';
        TestingUtility.insertWithAssert(testSettings);
        
        settingsInitialized = true;
    }
    @isTest static void test_post_success_1() {
        //pre-context
        Debug.turnDebugOn();
        initFieldMappings();
        
        //test
        Test.startTest();
        RestRequest req     = new RestRequest(); 
        RestResponse res    = new RestResponse();
      
      // pass the req and resp objects to the method         
      req.requestURI = 'https://cs8.salesforce.com/services/apexrest/InboundLead';  
      req.httpMethod = 'POST';

            //assign rest context
            RestContext.request     = req;
            RestContext.response    = res;
            Campaign c = new Campaign(Name='Test Campaign');
            insert c;
            //define container and set request Company and Reservable UUIDs
            WWTypes.InboundLead j = new WWTypes.InboundLead();
            j.company_name = 'A company';
            j.last_name = 'Doe';
            j.first_name = 'John';
            j.email = 'john@doe.com';
            j.campaign_sfid = c.Id;
            j.locale ='en-US';
            j.generate_journeys = false;
            j.phone = '9874563210';
            j.lead_source = 'test';
            j.lead_source_detail = 'test';
            j.lead_type = 'Office Space';
            j.Product_Interests = new List<String>{'Office Space','Residential Space'};
            
            //submit post
            RESTInboundLead.Response response = RESTInboundLead.doPost(j);
    
            //confirm response
            system.assertEquals(true, response.success);

            Lead[] Ks = [   SELECT id
                                        FROM Lead 
                                        WHERE email = :j.email 
                                        LIMIT 1
                                    ];
            system.assertEquals(
                1,
                Ks.size(),
                'A lead should be created'
            );

            Task[] Ts = [ SELECT id
                                    FROM Task
                                    WHERE WhoId = :Ks[0].id
                                    LIMIT 1
                                ];

            system.assertEquals(
                1,
                Ts.size(),
                'A task associated to the lead should be created'
            ); 
        
            List<Lead> leads = [ SELECT Id FROM Lead WHERE Id IN (SELECT LeadId FROM CampaignMember WHERE CampaignId =: c.Id AND LeadId != null) ];
            system.assertEquals(
                1,
                leads.size(),
                'A Lead associated to the Campaign should be created'
            );
        Test.stopTest();
    }
       
    @isTest static void test_post_success_2() {
        //pre-context
        
        //test
        Test.startTest();
        RestRequest req     = new RestRequest(); 
        RestResponse res    = new RestResponse();
      
      // pass the req and resp objects to the method         
      req.requestURI = 'https://cs8.salesforce.com/services/apexrest/InboundLead';  
      req.httpMethod = 'POST';

            //assign rest context
            RestContext.request     = req;
            RestContext.response    = res;
            Campaign c = new Campaign(Name='Test Campaign');
            insert c;
            //define container and set request Company and Reservable UUIDs
            WWTypes.InboundLead j       = new WWTypes.InboundLead();
            
            //submit post
            RESTInboundLead.Response response = RESTInboundLead.doPost(j);

        Test.stopTest();
    }
    
    //Anant Kumar on 9th May 2016
    //UseCase : If lead is exists with given email id;
    @isTest static void test_post_success_3() {
        //pre-context

        //test
        Test.startTest();
            RestRequest req     = new RestRequest(); 
        	RestResponse res    = new RestResponse();
      
        	// pass the req and resp objects to the method         
        	req.requestURI = System.URL.getSalesforceBaseURL().toExternalForm() + '/services/apexrest/InboundLead';  
        	req.httpMethod = 'POST';

            //assign rest context
            RestContext.request     = req;
            RestContext.response    = res;
            Campaign c = new Campaign(Name='Test Campaign');
            insert c;
            Account accRec = TestingUtility.createAccount('strAccountName', true);
            Contact referrerContact = TestingUtility.createContact(accRec.Id, 'strLastName', false);
        	referrerContact.Email = 'testreferrer@example.com';
        	TestingUtility.insertWithAssert(referrerContact);

            Lead leadRec1 = new Lead();
            leadRec1.LastName = 'Test Lead';
            leadRec1.Company = 'test123';
            leadRec1.Status = 'Open';
            leadRec1.LeadSource = 'wework.com';
            leadRec1.Email = 'test.lead@test123.com';
            Database.SaveResult result = TestingUtility.insertWithAssert(leadRec1);
        
            CampaignMember cm = new CampaignMember(CampaignId=c.Id ,LeadId=result.Id, Status='Sent');
            insert cm;
            //define container and set request Company and Reservable UUIDs
            WWTypes.InboundLead j       = new WWTypes.InboundLead();
            j.company_name                      = 'A company';
            j.last_name                             = 'Doe';
            j.first_name                            = 'John';
            j.email                                     = 'test.lead@test123.com';
            j.locale                                    ='en-US';
            j.campaign_sfid                             = c.Id;
            j.referrer_sfid                                  = referrerContact.Id;  
            j.Product_Interests  = new List<String>{'Office Space','Residential Space'}; 
            
            //submit post
            RESTInboundLead.Response response = RESTInboundLead.doPost(j);
    
            //confirm response
            //If a lead with given email id is exists.
            system.assertEquals(false, response.success);
    }
    
    @isTest static void test_post_success_5() {
        //pre-context

        //test
        Test.startTest();
            RestRequest req     = new RestRequest(); 
        RestResponse res    = new RestResponse();
      
      // pass the req and resp objects to the method         
      req.requestURI = System.URL.getSalesforceBaseURL().toExternalForm() + '/services/apexrest/InboundLead';  
      req.httpMethod = 'POST';

            //assign rest context
            RestContext.request     = req;
            RestContext.response    = res;
            Campaign c = new Campaign(Name='Test Campaign');
            insert c;
            Account accRec = TestingUtility.createAccount('strAccountName', true);
            Contact referrerContact = TestingUtility.createContact(accRec.Id, 'strLastName', false);
        	referrerContact.Email = 'testreferrer@example.com';
        	TestingUtility.insertWithAssert(referrerContact);

            Lead leadRec1 = new Lead();
            leadRec1.LastName = 'Test Lead';
            leadRec1.Company = 'test123';
            leadRec1.Status = 'Open';
            leadRec1.LeadSource = 'wework.com';
            leadRec1.Email = 'test.lead1@test123.com';
            Database.SaveResult result = TestingUtility.insertWithAssert(leadRec1);
        
            CampaignMember cm = new CampaignMember(CampaignId=c.Id ,LeadId=result.Id, Status='Sent');
            insert cm;
            //define container and set request Company and Reservable UUIDs
            WWTypes.InboundLead j       = new WWTypes.InboundLead();
            j.company_name                      = 'A company';
            j.last_name                             = 'Doe';
            j.first_name                            = 'John';
            j.email                                     = 'test.lead1@test123.com';
            j.locale                                    ='en-US';
            j.campaign_sfid                             = c.Id;
            j.referrer_sfid                                  = referrerContact.Id;  
            j.Product_Interests  = new List<String>{'Office Space','Residential Space'};
            
            //submit post
            RESTInboundLead.Response response = RESTInboundLead.doPost(j);
    
            //confirm response
            //If a lead with given email id is exists.
            system.assertEquals(false, response.success);
            Test.stopTest();
    }
    
    //Anant Kumar on 9th May 2016
    //UseCase : If contact is exists with given email id;
    @isTest static void test_post_success_4() {
        //pre-context

        //test
        Test.startTest();
            RestRequest req     = new RestRequest(); 
        RestResponse res    = new RestResponse();
      
      // pass the req and resp objects to the method         
      req.requestURI = System.URL.getSalesforceBaseURL().toExternalForm() + '/services/apexrest/InboundLead';  
      req.httpMethod = 'POST';

            //assign rest context
            RestContext.request     = req;
            RestContext.response    = res;
            Campaign c = new Campaign(Name='Test Campaign');
            insert c;
            Account accRec = TestingUtility.createAccount('strAccountName', true);
            Contact referrerContact = TestingUtility.createContact(accRec.Id, 'strLastName', false);
        	referrerContact.Email = 'testreferrer@example.com';
        	TestingUtility.insertWithAssert(referrerContact);
                
            Contact existingContact = TestingUtility.createContact(accRec.Id, 'existing Contact', false);
            existingContact.Email = 'test.lead@test123.com';
            TestingUtility.insertWithAssert(existingContact);
            
            Opportunity oppRec1 = TestingUtility.createOpportunity(accRec.Id, false);
            oppRec1.Primary_Member__c = existingContact.Id;
            TestingUtility.insertWithAssert(oppRec1);
            
            Map<String,Object> tourDataMap = new Map<String,Object>();
            tourDataMap.put('Scheduled_By__c', existingContact.Id);
            tourDataMap.put('Status__c', 'Scheduled');
            tourDataMap.put('Tour_Date__c', system.today().addDays(-1));
            tourDataMap.put('Start_Time__c', '9:00AM');
            Tour_Outcome__c contactRecord = (Tour_Outcome__c)TestingUtility.createTestRecords(Tour_Outcome__c.SObjectType, tourDataMap, true);
            
            //define container and set request Company and Reservable UUIDs
            WWTypes.InboundLead j       = new WWTypes.InboundLead();
            j.company_name                      = 'A company';
            j.last_name                             = 'Doe';
            j.first_name                            = 'John';
            j.email                                     = 'test.lead@test123.com';
            j.locale                                    ='en-US';
            j.campaign_sfid                             = c.Id;
            j.referrer_sfid                             = referrerContact.Id;  
            j.Product_Interests  = new List<String>{'Office Space','Residential Space'};
            
            //submit post
            RESTInboundLead.Response response = RESTInboundLead.doPost(j);
    
            //confirm response
            //If a lead with given email id is exists.
            system.assertEquals(false, response.success);
            Test.stopTest();
    }
    
    //UseCase : Test Inbound Lead for referral app.
    @isTest static void test_post_success_6() {
        //pre-context

        //test
        Test.startTest();
            RestRequest req     = new RestRequest(); 
        	RestResponse res    = new RestResponse();
      
        	// pass the req and resp objects to the method         
        	req.requestURI = System.URL.getSalesforceBaseURL().toExternalForm() + '/services/apexrest/InboundLead';  
        	req.httpMethod = 'POST';

            //assign rest context
            RestContext.request     = req;
            RestContext.response    = res;
            Campaign c = new Campaign(Name='Test Campaign');
            insert c;
            Account accRec = TestingUtility.createAccount('strAccountName', false);
        	accRec.Type = 'Prospect';
        	TestingUtility.insertWithAssert(accRec);
        
            Contact referrerContact = TestingUtility.createContact(accRec.Id, 'strLastName', false);
        	referrerContact.Email = 'testreferrer@example.com';
        	TestingUtility.insertWithAssert(referrerContact);
        	
            //define container and set request Company and Reservable UUIDs
            WWTypes.InboundLead j       = new WWTypes.InboundLead();
            j.company_name                      = 'A company';
            j.last_name                             = 'Doe';
            j.first_name                            = 'John';
            j.email                                     = 'test.lead@example.com';
            j.locale                                    ='en-US';
        	j.referrer_sfid                                  = referrerContact.Id;  
            j.Product_Interests  = new List<String>{'Office Space','Residential Space'}; 
            
            //submit post
            RESTInboundLead.Response response = RESTInboundLead.doPost(j);
    
            //confirm response
            //If a lead with given email id is exists.
            system.assertEquals(false, response.success);
        	system.assertEquals(1, [SELECT Id, Expires_On__c, Referrer__c FROM Reference__c].size());
        Test.stopTest();
    }
}