src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Journey__c.object
<CustomObject>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <fields>
        <fullName>NMD_Next_Contact_Date__c</fullName>
        <description>Date on which Journey Primary Member should be next contacted on.

This is key to manage the reminders for the Journey.</description>
        <label>Next Contact Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary Contact of the Journey</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If journey is for a Lead this will be the Primary Lead. Only Primary Contact or Primary Lead can be specified not both.</description>
        <label>Primary Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestJourneyDetailsController.cls
/**
 * This class should contain all the test methods related JourneyDetailsController 
 * 
 * @author  Dipak Pawar
 * @date    25/06/2016
 */

@isTest
public class TestJourneyDetailsController {
    /**
	 * ST-300 : Test method for JourneyDetailController Constructor
	 * @author  Dipak Pawar
	 * @date    21/June/2016
	 */
    static testMethod void TestJourneyDetailsController() {
		//Test Account created for testContact.
        Account testAccount = new Account();
        testAccount.Name = 'Test Account';
		insert testAccount;
		//Test Contact created for testJourney.
        Contact testContact = new Contact();
    	 	testContact.AccountId = testAccount.Id;
    	 	testContact.firstname = 'TestFirstName';
    	 	testContact.lastname = 'TestLastName';
         	testContact.Email = 'Test111@example.com';
         	testContact.Status__c = 'active';
        insert testContact;
	    System.assertNotEquals(testContact.Id, null);
		
		//Test Journey for JourneyDetailController.        
	    Journey__c testJourney = new Journey__c();
	    testJourney.Name = 'testJourneyName';
	    testJourney.CurrencyIsoCode = 'USD';
	    testJourney.Primary_Contact__c = testContact.Id;
        testJourney.NMD_Next_Contact_Date__c = Date.today();
	    TestingUtility.insertWithAssert(testJourney);
        System.debug(LoggingLevel.ERROR,'testJourney1 ::'+testJourney);
	    ApexPages.StandardController testStandardController = new ApexPages.StandardController(testJourney);
	    JourneyDetailController testObject = new JourneyDetailController(testStandardController);
        
        //JourneyDetails Page with journeyId as a parameter.
        PageReference testPageReference = new PageReference('/apex/JourneyDetails');
        testPageReference.getParameters().put('journeyId', testJourney.Id);
        Test.setCurrentPageReference(testPageReference);
    }
    
    static testMethod void TestJourneyDetailsController_ForLead() {
		//Test Account created for testContact.
        Lead leadNew = new Lead(LastName = 'Test Lead Last Name', Company = 'Test Company', Email = 'test@example.com', Phone = '1212121125', Generate_Journey__c = false);
        insert leadNew;
		//Test Journey for JourneyDetailController.        
	    Journey__c testJourney = new Journey__c();
	    testJourney.Name = 'testJourney';
	    testJourney.CurrencyIsoCode = 'USD';
	    testJourney.Primary_Lead__c = leadNew.Id;
        testJourney.NMD_Next_Contact_Date__c = Date.today();
	    TestingUtility.insertWithAssert(testJourney);
	    ApexPages.StandardController testStandardController = new ApexPages.StandardController(testJourney);
	    JourneyDetailController testObject = new JourneyDetailController(testStandardController);
        
        //JourneyDetails Page with journeyId as a parameter.
        PageReference testPageReference = new PageReference('/apex/JourneyDetails');
        testPageReference.getParameters().put('journeyId', testJourney.Id);
        Test.setCurrentPageReference(testPageReference);
    }
}