src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Journey__c.object
<CustomObject>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <fields>
        <fullName>Lost_Reason__c</fullName>
        <description>Reason why we lost the journey</description>
        <label>Lost Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor Solution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fake Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unrelated to Sales Inquiries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NMD_Next_Contact_Date__c</fullName>
        <description>Date on which Journey Primary Member should be next contacted on.

This is key to manage the reminders for the Journey.</description>
        <label>Next Contact Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary Contact of the Journey</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If journey is for a Lead this will be the Primary Lead. Only Primary Contact or Primary Lead can be specified not both.</description>
        <label>Primary Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referrer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referrer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Journeys (Referrer)</relationshipLabel>
        <relationshipName>Journeys1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage of the Journey, which will tell us the maximum progress the customer has made.

It will not give us latest Stage but will give maximum stage that is if the journey is completed or lost, or if it is stuck in waitlist.</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Tour Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tour Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed-Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed-Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Triggers__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>We are going to use this object to activate or deactivate various triggers we will be writing so we can easily deactivate triggers in case of errors or mass upload if required.</description>
    <fields>
        <fullName>Journey_setPrimaryLeadToUnqualified__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If  Journey stage is Completed-Lost then set the Primary Lead as Unqualified.</description>
        <label>Journey setPrimaryLeadToUnqualified</label>
        <type>Checkbox</type>
    </fields>
    <label>Triggers</label>
</CustomObject>

src/classes/JourneyTriggerHandlerTest.cls
@isTest
public class JourneyTriggerHandlerTest {
    private static testMethod void testSetPrimaryLeadToUnqualified() {
        
        Triggers__c triggerSettings = Triggers__c.getInstance();
		triggerSettings.Journey_setPrimaryLeadToUnqualified__c = true;
		upsert triggerSettings;
		
		Setting__c testSettings = new Setting__c();
        testSettings.Name = 'LeadJourneyTrigger';
        testSettings.Data__c = '[{"LeadStatus":"Unqualified","JourneyStage":"Completed-Lost"}]';
        TestingUtility.upsertWithAssert(testSettings);
		
    	//Test Account created for testContact.
        Lead testLead = new Lead(LastName = 'Test Lead Last Name', Company = 'Test Company', Email = 'test@example.com', Phone = '1212121125', Generate_Journey__c = false);
        TestingUtility.insertWithAssert(testLead);
		//Test Journey for JourneyDetailController.        
	    Journey__c testJourney = new Journey__c();
	    testJourney.Name = 'testJourney';
	    testJourney.CurrencyIsoCode = 'USD';
	    testJourney.Primary_Lead__c = testLead.Id;
        testJourney.NMD_Next_Contact_Date__c = Date.today();
        testJourney.Lost_Reason__c = 'Not Interested';
	    TestingUtility.insertWithAssert(testJourney);
	    
        testJourney.Stage__c = 'Completed-Lost';
        update testJourney;
        List<Lead> lead = new List<Lead>([select Id, Name, Status, Unqualified_Reason__c from Lead where Id =: testLead.Id]);
        System.assertEquals('Unqualified', lead[0].Status);
        System.assertEquals('Not interested', lead[0].Unqualified_Reason__c);
    }
    
    static testMethod void testUpdateActiveReferrerOnJourney(){
    	Account accRec = new Account();
    	accRec.Name='Test Account' ;
    	insert accRec;
    	
    	Contact testContact = new Contact(
    	   AccountId =  accRec.Id,	
           firstname = 'TestFirstName',
           lastname = 'TestLastName',
           email = 'primary123@example.com',
           Status__c = 'active',
		   Referrer__c  = null	          
        );
        insert testContact;
                
        Contact referrer1 = new Contact(
    	   AccountId =  accRec.Id,	
           firstname = 'TestFirstName',
           lastname = 'TestLastName',
           email = 'TesT888@example.com',
           Status__c = 'active',
		   Referrer__c  = null	          
        );
        insert referrer1;
    	 
        Reference__c testReference = new Reference__c(Referenced_Email__c = 'primary123@example.com', IsActive__c = true,Expires_On__c = (Date.today()).addDays(2),Referrer__c = referrer1.Id);
        insert testReference;
        
        Journey__c testJourney = new Journey__c();
        testJourney.Name = 'testJourney';
        testJourney.NMD_Next_Contact_Date__c = Date.today();
        testJourney.Primary_Contact__c = testContact.Id;
        insert testJourney;
       
        Journey__c journey = [select Id,Referrer__c from Journey__c where Id=: testJourney.Id];
        system.assertEquals(referrer1.Id,journey.Referrer__c);
   
   		  Contact referrer2 = new Contact(
    	   AccountId =  accRec.Id,	
           firstname = 'TestFirstName',
           lastname = 'TestLastName',
           email = 'TesT456@example.com',
           Status__c = 'active',
		   Referrer__c  = null	          
        );
        insert referrer2;
        
        Lead testLead = new Lead(FirstName = 'Test',
             LastName = 'Lead',
             Company = 'TestCompany',
             Status = 'Open',
             Locations_Interested__c = 'B1; B2;',
             Office_Type__c = 'Shared Desk; DailyDesk;',
             Email = 'TEST1994@example.com'
            );
        insert testLead;
        
       	Reference__c testReference1 = new Reference__c(Referenced_Email__c = 'TEST1994@example.com', IsActive__c = true,Expires_On__c = (Date.today()).addDays(2),Referrer__c = referrer2.Id);
        insert testReference1;
        
        Journey__c testJourney2 = new Journey__c();
        testJourney2.Name = 'testJourney';
        testJourney2.NMD_Next_Contact_Date__c = Date.today();
        testJourney2.Primary_Lead__c = testLead.Id;
        insert testJourney2;
               
        Journey__c journey1 = [select Id,Referrer__c from Journey__c where Id =:testJourney2.Id];
        system.assertEquals(referrer2.Id,journey1.Referrer__c);
       
    }
}