src/objects/Journey__c.object
<CustomObject>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary Contact of the Journey</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If journey is for a Lead this will be the Primary Lead. Only Primary Contact or Primary Lead can be specified not both.</description>
        <label>Primary Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/JourneyDetailController.cls
public class JourneyDetailController {
    public String journeyId {get; set;}
    public Journey__c journey {get; set;} 
    public Contact contact {get; set;}
    public Lead lead {get; set;}
    public String toId {get; set;}
    public Map<string,List<EmailTemplate>> mapEmailTemplate {get; set;}
    public JourneyDetailController(ApexPages.StandardController controller) {
        journeyId = controller.getId();
        if(journeyId != null){
        		journey = [Select Id,Name,Primary_Contact__c,Primary_Lead__c From Journey__c Where Id=:journeyId];

                if(journey.Primary_Contact__c != null){
                	contact =[SELECT Id,Name FROM Contact Where Id=:journey.Primary_Contact__c Limit 1];
                    toId = contact.Id;
                }
                if(journey.Primary_Lead__c != null){
                	lead = 	[SELECT Id,Name FROM Lead Where Id=:journey.Primary_Lead__c Limit 1];
                    toId =  lead.Id;
                }
            
           	List<EmailTemplate> lstEmailTemplates = [SELECT Name, Folder.Id,Folder.name, Id FROM EmailTemplate order by Name]; 
            mapEmailTemplate = new Map<string,List<EmailTemplate>>();  

            for(EmailTemplate currentEmailTemplate : lstEmailTemplates) { 
                if(currentEmailTemplate.Folder.name != null) {
                    if(mapEmailTemplate.containsKey(currentEmailTemplate.Folder.name)) {
                    List<EmailTemplate> lstEmailTemplate =  mapEmailTemplate.get(currentEmailTemplate.Folder.name);
                    lstEmailTemplate.add(currentEmailTemplate);
                    mapEmailTemplate.put(currentEmailTemplate.Folder.name,lstEmailTemplate);
                    }
                    else {
                        List<EmailTemplate> lstEmailTemplate = new List<EmailTemplate>();
                        lstEmailTemplate.add(currentEmailTemplate);
                        mapEmailTemplate.put(currentEmailTemplate.Folder.name,lstEmailTemplate);
                    } 
                }   
            }  	  
        }
    }    
}