src/objects/Journey__c.object
<CustomObject>
    <description>We are going to use this object as Sales Journey of the user. Which begins when a person shows interest in one of our products or we decide to reach out to show our products.</description>
    <fields>
        <fullName>NMD_Next_Contact_Date__c</fullName>
        <description>Date on which Journey Primary Member should be next contacted on.

This is key to manage the reminders for the Journey.</description>
        <label>Next Contact Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Primary Contact of the Journey</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If journey is for a Lead this will be the Primary Lead. Only Primary Contact or Primary Lead can be specified not both.</description>
        <label>Primary Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Journeys</relationshipLabel>
        <relationshipName>Journeys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage of the Journey, which will tell us the maximum progress the customer has made.

It will not give us latest Stage but will give maximum stage that is if the journey is completed or lost, or if it is stuck in waitlist.</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Tour Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tour Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed-Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed-Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Journey</label>
    <nameField>
        <label>Customer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestInboundCallController.cls
@isTest
public class TestInboundCallController
{
  
		static testMethod void testContactAndRelated(){
		//Insert Account
		Account acc = new Account(Name = 'Test Account');
		insert acc;
        
		//Insert two contacts
		Contact c1 = new Contact(FirstName = 'Test',
								LastName = 'Contact1',
								AccountId = acc.Id,
								Email = 'Test111@example.com',
								Phone = '3256987425');
		insert c1;
		Contact c2 = new Contact(FirstName = 'Test',
								LastName = 'Contact2',
								AccountId = acc.Id,
								Phone = '3256987455',
								Email = 'Test112@example.com',
								LeadSource = 'Inbound Call');
		insert c2;
		
		Lead lead = new Lead(
    	 	FirstName = 'Test', 
    	 	LastName = 'Test',
    	 	Company = 'Test',
    	 	Email = 'Test111@example.com',
    	 	LeadSource = 'other',
    	    Status = 'TestStatus',
    	    CurrencyIsoCode = 'USD'
    	);
    	 	  
        insert lead;
        
        
		Journey__c objTestJourny1 = new Journey__c();
		objTestJourny1.Name = 'Test Customer1';
		objTestJourny1.Stage__c = 'Started';
		objTestJourny1.Primary_Contact__c = c1.Id;
		objTestJourny1.NMD_Next_Contact_Date__c=Date.today().addDays(4);
		TestingUtility.insertWithAssert(objTestJourny1);
		
		objTestJourny1 = new Journey__c();
		objTestJourny1.Name = 'Test Customer1';
		objTestJourny1.Stage__c = 'Started';
		objTestJourny1.Primary_Lead__c = lead.Id;
		objTestJourny1.NMD_Next_Contact_Date__c=Date.today().addDays(4);
		TestingUtility.insertWithAssert(objTestJourny1);
       
		// WeworkEngine.createJourneryAndJourneyContact(c2.Id,c2.LeadSource);
       
		InboundCallController.getContactAndRelatedJoureny('3256987425','','', (String)c1.Id);
		InboundCallController.getContactAndRelatedJoureny('Test111@example.com','','','');
	}
}