src/objects/Triggers__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>We are going to use this object to activate or deactivate various triggers we will be writing so we can easily deactivate triggers in case of errors or mass upload if required.</description>
    <fields>
        <fullName>Change_Owner_To_First_User_Who_Respond__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Change Owner To First User Who Respond</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Close_all_open_inbound_lead_activities__c</fullName>
        <defaultValue>true</defaultValue>
        <description>On or off close all open inbound lead activities on tour booking.</description>
        <label>Close all open inbound lead activities</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Copy_Fields_From_Last_Opportunity__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whenever a new Opportunity gets created we need to give credit to the Source, utm and referrer of the latest opportunity created in last 60 days.</description>
        <label>Copy Fields From Last Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_Deal_On_Opportunity_Create__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Create_Deal_On_Opportunity_Create</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_Journey_Contact_On_Journey_Create__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use to turn on or off trigger for creating &apos;Journey Contact&apos; on Journey Record Create</description>
        <label>Create Journey Contact On Journey Create</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Create_Journey_Contact_On_Member_Change__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Fire method to create new Journey Contact Record when primary member change on Journey objects record</description>
        <label>Create Journey Contact On Member Change</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deals_Set_Closed_Deal_Status_To_Blank__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Deals_Set_Closed_Deal_Status_To_Blank</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Debug__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If this field is checked, Error level logging is turned on for Debug logs in the code so we can easily see error level logs and find the trace. In production this should be turned off unless debugging.</description>
        <label>Debug</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Generate_Building_Interests__c</fullName>
        <defaultValue>true</defaultValue>
        <description>On or off Generate Building Interests</description>
        <label>Generate Building Interests</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Upate_Encoded_ID__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Opportunity_Upate_Encoded_ID</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Task_Call_Result_Update_Journey_NMD_Date__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use to turn on or off trigger which update NMD Next Contact Date on Task with  &quot;Call Result&quot; starting with &quot;Left VM:&quot;  or  &quot;No Answer/Busy&quot;</description>
        <label>Task Call Result Update Journey NMD Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tour_Scheduled_Convert_Lead__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Turn on/off Tour Scheduled Convert Lead functionality on Tour trigger.</description>
        <label>Tour Scheduled Convert Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_Building_Interest_On_Lead__c</fullName>
        <defaultValue>true</defaultValue>
        <description>It will update the Building Interested In lookup from Location Interested In field</description>
        <label>Update Building Interest On Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_ClosedWon_Accounts__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Turn on/off Update ClosedWon Accounts functionality from Opportunity triggers</description>
        <label>Update ClosedWon Accounts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_Contact_Most_Recent_Opp_Stage__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Update_Contact_Most_Recent_Opp_Stage</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_Deal_On_Opportunity_Update__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Update_Deal_On_Opportunity_Update</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_Journey_Stage_To_CompletedLost__c</fullName>
        <defaultValue>true</defaultValue>
        <description>It will fire whenever Task__c Call Result field updated to Do Not Call and it change the Journey Stage to Completed-Lost</description>
        <label>Update Journey Stage To CompletedLost</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_Most_Recent_Tour_Date__c</fullName>
        <defaultValue>true</defaultValue>
        <description>On or off  update most recent tour date functionality on tour trigger.</description>
        <label>Update Most Recent Tour Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_Name_for_EnterpriseSolution_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <description>turn on or off oppotunity trigger for update opportunity name for Enterprise solutions.</description>
        <label>Update Name for EnterpriseSolution Type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_Opportunity_Name__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Update_Opportunity_Name</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_Space_BasedOn_SpaceUUID__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Update_Space_BasedOn_SpaceUUID</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_Task_Due_Date_From_Journey_NMD__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This custom setting is use to turn on or off task trigger &apos;updateTaskDueDateToJournyNextContactDate&apos; which update task due date from Journey NMD Next Contact Date</description>
        <label>Update Task Due Date From Journey NMD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_Task_Owner__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Use to turn on or off trigger for update ownerId for task after Insert/Update of task record.</description>
        <label>Update Task Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_Tour_Enditme__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Update_Tour_Enditme</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_WeLive_Opportunity_Type__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Update_WeLive_Opportunity_Type</label>
        <type>Checkbox</type>
    </fields>
    <label>Triggers</label>
</CustomObject>

src/classes/Settings.cls
/* Created by @hemanshu.shah@enzigma.com on 24 Apr 2016
* This class should contain all the triggers related to Settings
* As well as static methods to retreive Settings with Caching for optimized usage.
* 
*/

public class Settings {
    /* Created by hemanshu.shah@enzigma.com on 24 Apr 2016
     * This method used by the trigger to update the Unique Key so there are no duplicate Settings with same name.
     * In future if we use user or profile based settings, this should be modified to make sure there are no duplicates.
     */    
    public static void UpdateUniqueKey(Setting__c[] settings){
        for(Setting__c setting : settings ){
            setting.Unique_Key__c = setting.Name;
        }
    }

	static Triggers__c triggerSettings = null;
	public static Triggers__c getTriggerSettings(){
		if( triggerSettings == null ) {
			triggerSettings = Triggers__c.getOrgDefaults();
			if( String.isBlank(triggerSettings.Id) ) {

				triggerSettings.Debug__c = true;
				triggerSettings.Change_Owner_To_First_User_Who_Respond__c = true;
				triggerSettings.Close_All_Open_Inbound_Lead_Activities__c = true;
				triggerSettings.Copy_Fields_From_Last_Opportunity__c = true;
				triggerSettings.Create_Deal_On_Opportunity_Create__c = true;
				triggerSettings.Create_Journey_Contact_On_Journey_Create__c = true;
				triggerSettings.Create_Journey_Contact_On_Member_Change__c = true;
				triggerSettings.Deals_Set_Closed_Deal_Status_To_Blank__c = true;
				triggerSettings.Generate_Building_Interests__c = true;
				triggerSettings.Opportunity_Upate_Encoded_ID__c = true;
				triggerSettings.Task_Call_Result_Update_Journey_NMD_Date__c = true;
				triggerSettings.Tour_Scheduled_Convert_Lead__c = true;
				triggerSettings.Update_Building_Interest_On_Lead__c = true;
				triggerSettings.Update_ClosedWon_Accounts__c = true;
				triggerSettings.Update_Contact_Most_Recent_Opp_Stage__c = true;
				triggerSettings.Update_Deal_On_Opportunity_Update__c = true;
				triggerSettings.Update_Journey_Stage_To_CompletedLost__c = true;
				triggerSettings.Update_Most_Recent_Tour_Date__c = true;
				triggerSettings.Update_Name_for_EnterpriseSolution_Type__c = true;
				triggerSettings.Update_Opportunity_Name__c = true;
				triggerSettings.Update_Space_BasedOn_SpaceUUID__c = true;
				triggerSettings.Update_Task_Due_Date_From_Journey_NMD__c = true;
				triggerSettings.Update_Task_Owner__c = true;
				triggerSettings.Update_Tour_Enditme__c = true;
				triggerSettings.Update_WeLive_Opportunity_Type__c = true;
		        
				upsert triggerSettings;
			}
		}
		return triggerSettings;
	}
    
    /* Created by hemanshu.shah@enzigma.com on 24 Apr 2016
     * This method caches queried setttings so for subsequent usage it does not query it again.
     */
    static Map<String,Setting__c> mapSettingsToName = new Map<String, Setting__c>();
    public static Setting__c get(String strName){
        strName = strName.toLowerCase();
        if( !mapSettingsToName.containsKey(strName) ){
        	Setting__c[] settings = [Select Id, Name, Data__c From Setting__c Where Name = :strName];
            if( settings.size() > 0 ) {
                mapSettingsToName.put(strName, settings[0]);
                return settings[0];
            }
            return null;
        }
        return mapSettingsToName.get(strName);
    }
    
    /* Created by hemanshu.shah@enzigma.com on 24 Apr 2016
     * This method caches all given settings using one query so
     * query is not fired for each setting
     */
    public static object get(string strName, Type type){
        Setting__c setting = get(strName);
		if( setting != null )
			return JSON.deserialize(setting.Data__c, type);
		return null;
    }
    
    /* Created by hemanshu.shah@enzigma.com on 24 Apr 2016
     * This method caches all given settings using one query so
     * query is not fired for each setting
     */
    public static void LoadSettings(String[] names){
        Setting__c[] settings = [Select Id, Name, Data__c From Setting__c Where Name in :names];
        for(Setting__c setting : settings){
            mapSettingsToName.put(setting.Name.toLowerCase(), setting);
        }
    }
    
    /* Created by hemanshu.shah@enzigma.com on 24 Apr 2016
     * This method caches all given field mappings settings using one query so
     * query is not fired for each setting
     */
    public static void LoadFieldMappings(){
        Setting__c[] settings = [Select Id, Name, Data__c From Setting__c Where Name Like 'FieldMappings:%'];
        for(Setting__c setting : settings){
            mapSettingsToName.put(setting.Name.toLowerCase(), setting);
        }
    }
    
    /* Created by hemanshu.shah@enzigma.com on 23 June 2016
     * Use this method to load field mapping which always returns map of string of string
     * it internally uses cached data to avoid queries
     */
    public static Database.UpsertResult saveFieldMappings(String strName, Settings.FieldMappings mappings){
        String strSettingsName = 'FieldMappings:' + strName;
        Setting__c settings = get(strSettingsName);
        if( settings == null )
            settings = new Setting__c(Name = strSettingsName);
        settings.Data__c = JSON.serialize(mappings);
        return Database.upsert(settings);
    }
    
    /* Created by hemanshu.shah@enzigma.com on 24 Apr 2016
     * Use this method to load field mapping which always returns map of string of string
     * it internally uses cached data to avoid queries
     */
    static Map<String, FieldMappings> mapFieldMappings = new Map<String, FieldMappings>();
    public static FieldMappings getFieldMappings(String strName){
        if( mapFieldMappings.containsKey(strName))
            return mapFieldMappings.get(strName);
        
        Setting__c setting = get('FieldMappings:' + strName);
		if( setting == null )
			return null;
		
		Settings.FieldMappings fieldMappings = (Settings.FieldMappings)JSON.deserialize(setting.Data__c, Settings.FieldMappings.class);

        mapFieldMappings.put(strName, fieldMappings);
        return fieldMappings;
    }
    
    public class FieldMappings {
        public integer version {get; set;}
        public Map<String, MappedField> mappings{get; set;}
    }
    
    public class MappedField {
        
        public MappedField(String strValue){
            this(strValue, false);
        }
        
        public MappedField(String strValue, Boolean isValue){
            this.isvalue = isValue;
            if( isValue )
                this.value = strValue;
            else
            	this.fieldname = strValue;
            this.overwrite = false;
        }

        public boolean isvalue {get; set;}
        public String value{get; set;}
        public String fieldname {get;set;}
        public boolean overwrite {get; set;}
    }
}